export default [
  {
    title: "Demon Slayer",
    genre: ["Action", "Fantasy"],
    episodes: 55,
    status: "Ongoing",
    releaseYear: 2019,
    rating: 8.7,
    studio: "Ufotable",
  },
  {
    title: "Attack on Titan",
    genre: ["Action", "Drama", "Fantasy"],
    episodes: 87,
    status: "Finished",
    releaseYear: 2013,
    rating: 9.1,
    studio: "MAPPA",
  },
  {
    title: "Naruto",
    genre: ["Action", "Adventure"],
    episodes: 220,
    status: "Finished",
    releaseYear: 2002,
    rating: 8.3,
    studio: "Studio Pierrot",
  },
  {
    title: "Naruto Shippuden",
    genre: ["Action", "Adventure"],
    episodes: 500,
    status: "Finished",
    releaseYear: 2007,
    rating: 8.6,
    studio: "Studio Pierrot",
  },
  {
    title: "Jujutsu Kaisen",
    genre: ["Action", "Supernatural"],
    episodes: 47,
    status: "Ongoing",
    releaseYear: 2020,
    rating: 8.8,
    studio: "MAPPA",
  },
  {
    title: "One Piece",
    genre: ["Adventure", "Action", "Fantasy"],
    episodes: 1100,
    status: "Ongoing",
    releaseYear: 1999,
    rating: 9.0,
    studio: "Toei Animation",
  },
];
