export default [
  {
    title: "Demon Slayer",
    genre: ["Action", "Fantasy"],
    episodes: 55,
    status: "Ongoing",
    releaseYear: 2019,
    rating: 8.7,
    studio: "Ufotable",
  },
  {
    title: "Attack on Titan",
    genre: ["Action", "Drama", "Fantasy"],
    episodes: 87,
    status: "Finished",
    releaseYear: 2013,
    rating: 9.1,
    studio: "MAPPA",
  },
  {
    title: "Naruto",
    genre: ["Action", "Adventure"],
    episodes: 220,
    status: "Finished",
    releaseYear: 2002,
    rating: 8.3,
    studio: "Studio Pierrot",
  },
  {
    title: "Naruto Shippuden",
    genre: ["Action", "Adventure"],
    episodes: 500,
    status: "Finished",
    releaseYear: 2007,
    rating: 8.6,
    studio: "Studio Pierrot",
  },
  {
    title: "Jujutsu Kaisen",
    genre: ["Action", "Supernatural"],
    episodes: 47,
    status: "Ongoing",
    releaseYear: 2020,
    rating: 8.8,
    studio: "MAPPA",
  },
  {
    title: "One Piece",
    genre: ["Adventure", "Action", "Fantasy"],
    episodes: 1100,
    status: "Ongoing",
    releaseYear: 1999,
    rating: 9.0,
    studio: "Toei Animation",
  },
  {
    title: "Bleach",
    genre: ["Action", "Supernatural"],
    episodes: 366,
    status: "Finished",
    releaseYear: 2004,
    rating: 8.2,
    studio: "Studio Pierrot",
  },
  {
    title: "My Hero Academia",
    genre: ["Action", "Superhero"],
    episodes: 138,
    status: "Ongoing",
    releaseYear: 2016,
    rating: 8.4,
    studio: "Bones",
  },
  {
    title: "Fullmetal Alchemist: Brotherhood",
    genre: ["Action", "Adventure", "Fantasy"],
    episodes: 64,
    status: "Finished",
    releaseYear: 2009,
    rating: 9.2,
    studio: "Bones",
  },
  {
    title: "Death Note",
    genre: ["Thriller", "Supernatural"],
    episodes: 37,
    status: "Finished",
    releaseYear: 2006,
    rating: 9.0,
    studio: "Madhouse",
  },
  {
    title: "Tokyo Ghoul",
    genre: ["Action", "Horror"],
    episodes: 48,
    status: "Finished",
    releaseYear: 2014,
    rating: 7.9,
    studio: "Pierrot",
  },
  {
    title: "Sword Art Online",
    genre: ["Action", "Adventure", "Romance"],
    episodes: 96,
    status: "Ongoing",
    releaseYear: 2012,
    rating: 7.8,
    studio: "A-1 Pictures",
  },
  {
    title: "Hunter x Hunter",
    genre: ["Adventure", "Fantasy"],
    episodes: 148,
    status: "Finished",
    releaseYear: 2011,
    rating: 9.1,
    studio: "Madhouse",
  },
  {
    title: "Black Clover",
    genre: ["Action", "Fantasy"],
    episodes: 170,
    status: "Finished",
    releaseYear: 2017,
    rating: 8.0,
    studio: "Studio Pierrot",
  },
  {
    title: "Dragon Ball Z",
    genre: ["Action", "Adventure"],
    episodes: 291,
    status: "Finished",
    releaseYear: 1989,
    rating: 8.7,
    studio: "Toei Animation",
  },
  {
    title: "Chainsaw Man",
    genre: ["Action", "Horror", "Supernatural"],
    episodes: 12,
    status: "Ongoing",
    releaseYear: 2022,
    rating: 8.6,
    studio: "MAPPA",
  },
  {
    title: "Spy x Family",
    genre: ["Comedy", "Action"],
    episodes: 37,
    status: "Ongoing",
    releaseYear: 2022,
    rating: 8.5,
    studio: "Wit Studio",
  },
  {
    title: "One Punch Man",
    genre: ["Action", "Comedy"],
    episodes: 24,
    status: "Ongoing",
    releaseYear: 2015,
    rating: 8.8,
    studio: "Madhouse",
  },
  {
    title: "Fairy Tail",
    genre: ["Adventure", "Fantasy"],
    episodes: 328,
    status: "Finished",
    releaseYear: 2009,
    rating: 7.7,
    studio: "A-1 Pictures",
  },
  {
    title: "Blue Lock",
    genre: ["Sports", "Action"],
    episodes: 24,
    status: "Ongoing",
    releaseYear: 2022,
    rating: 8.3,
    studio: "8bit",
  },
];
